### ISSUE TITLE
SIGSEGV in examples after latest changes.

### ISSUE THREAD

**Issue by Potpourri** [gfx-rs/gfx-rs#649]
After `Fixed shader values allocation hazard #646` and `Added index buffer flag #647` `gfx_examples` crashed with SIGSEGV.
I tested on linux.
Gdb backtrace for cube example:
```
#0  0x0000555555574a6a in cube::atomic::atomic_sub<usize> (
    dst=0x5555556b71b1 <str44968+1>, val=1, order=Release)
    at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/atomic.rs:958
#1  0x00005555555749d0 in cube::atomic::AtomicUsize::fetch_sub (
    self=0x5555556b71b1 <str44968+1>, val=1, order=Release)
    at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/atomic.rs:730
#2  0x000055555559fa73 in cube::arc::Arc<T>.Drop::drop (self=0x7ffff242f070)
    at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/arc.rs:337
#3  0x000055555559f9de in alloc..arc..Arc$LT$u32$GT$::glue_drop.8134::h90d5cc1669d36480 ()
#4  0x00005555555a09fe in gfx..device..handle..Texture$LT$gfx_device_gl..GlResources$GT$::glue_drop.8162::h3fc166aae1ce97bf ()
#5  0x00005555555ab9e6 in _$LP$gfx..device..handle..Texture$LT$gfx_device_gl..GlResources$GT$$C$$u20$core..option..Option$LT$gfx..device..handle..Sampler$LT$gfx_device_gl..GlResources$GT$$GT$$RP$::glue_drop.8497::h08bff23a018ac6ad ()
#6  0x00005555555c54c7 in fnfn (id=0 '\000') at src/cube/main.rs:43
#7  0x00005555555c534f in cube::option::Option<T>::map_or<(),closure> (
    self=Some = {...}, def=0, f={void (struct (u8))} 0x7fffffff97a0)
    at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:440
```
Before these changes all worked fine.

**Comment by kvark** [comment]
Awesome, we'll patch it ASAP. Thanks for the report!

**Comment by Potpourri** [comment]
Just to confirm all works, thank you!

**Comment by kvark** [comment]
Awesome, thanks @Potpourri !
