### ISSUE TITLE
Rust 1.0 compatibility

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#676]
Currently unresolved problems:
- [x] syntax extensions (`gfx_macros`)
    - find a way to program it with simple macros
- [x] `Arc` needs an `is_unique` of sorts
    - change to `Rc`, at least this one should work
- [x] `from_u32`
- [x] `ref_slice`

**Comment by KingOfThePirates** [comment]
Is this related or should I make a new issue?

Output:
```bash
me@me-desktop ~/projects/mypiston2 $ cargo run -v
   Compiling gfx_macros v0.1.10 (https://github.com/gfx-rs/gfx_macros#22981219)
     Running `rustc /home/me/.cargo/git/checkouts/gfx_macros-20b8916c81d6b4ed/master/src/lib.rs --crate-name gfx_macros --crate-type dylib -C prefer-dynamic -g -C metadata=996769dbcfbdc64a -C extra-filename=-996769dbcfbdc64a --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps -Awarnings`
       Fresh rustc-serialize v0.3.12
       Fresh libc v0.1.5
       Fresh shader_version v0.0.6 (https://github.com/pistondevelopers/shader_version#14aa73be)
       Fresh khronos_api v0.0.5
       Fresh bitflags v0.1.1
   Compiling gl_generator v0.0.23
     Running `rustc /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/gl_generator-0.0.23/lib.rs --crate-name gl_generator --crate-type lib -g -C metadata=82ab4c4fe082fae1 -C extra-filename=-82ab4c4fe082fae1 --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern log=/home/me/projects/mypiston2/target/debug/deps/liblog-54cf393d3c69686f.rlib --extern xml=/home/me/projects/mypiston2/target/debug/deps/libxml-3e674a70152e28f6.rlib --extern khronos_api=/home/me/projects/mypiston2/target/debug/deps/libkhronos_api-4b6881d34c5ba88e.rlib -Awarnings`
   Compiling gl_generator v0.0.23 (https://github.com/bjz/gl-rs#3ebf1cfe)
     Running `rustc /home/me/.cargo/git/checkouts/gl-rs-5020f97825182d66/master/gl_generator/lib.rs --crate-name gl_generator --crate-type lib -g -C metadata=303adfd0fabbd040 -C extra-filename=-303adfd0fabbd040 --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern khronos_api=/home/me/projects/mypiston2/target/debug/deps/libkhronos_api-4ca4e769faea81a4.rlib --extern log=/home/me/projects/mypiston2/target/debug/deps/liblog-54cf393d3c69686f.rlib --extern xml=/home/me/projects/mypiston2/target/debug/deps/libxml-3e674a70152e28f6.rlib -Awarnings`
   Compiling gfx v0.2.5 (https://github.com/gfx-rs/gfx-rs#31f69587)
     Running `rustc /home/me/.cargo/git/checkouts/gfx-rs-93bce98024942039/master/src/lib.rs --crate-name gfx --crate-type lib -g -C metadata=071b9a54eef8c4dd -C extra-filename=-071b9a54eef8c4dd --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern log=/home/me/projects/mypiston2/target/debug/deps/liblog-54cf393d3c69686f.rlib --extern bitflags=/home/me/projects/mypiston2/target/debug/deps/libbitflags-518ea12e21428edd.rlib --extern draw_state=/home/me/projects/mypiston2/target/debug/deps/libdraw_state-b1713f38ae84493e.rlib -Awarnings`
       Fresh khronos_api v0.0.5 (https://github.com/bjz/gl-rs#3ebf1cfe)
       Fresh sdl2-sys v0.0.34 (https://github.com/AngryLawyer/rust-sdl2#8e00e516)
       Fresh gl_common v0.0.4 (https://github.com/bjz/gl-rs#3ebf1cfe)
       Fresh clock_ticks v0.0.5 (https://github.com/tomaka/clock_ticks#cdb6499b)
   Compiling sdl2 v0.0.35 (https://github.com/AngryLawyer/rust-sdl2#8e00e516)
     Running `rustc /home/me/.cargo/git/checkouts/rust-sdl2-8facfb557b6c1670/master/src/sdl2/lib.rs --crate-name sdl2 --crate-type lib -g --cfg feature="default" -C metadata=a064b7049d699f0c -C extra-filename=-a064b7049d699f0c --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern libc=/home/me/projects/mypiston2/target/debug/deps/liblibc-8c77960f0e8d4e86.rlib --extern sdl2_sys=/home/me/projects/mypiston2/target/debug/deps/libsdl2_sys-ae2c8ed03a451f47.rlib --extern rand=/home/me/projects/mypiston2/target/debug/deps/librand-7b0a3af7ae4685dc.rlib --extern bitflags=/home/me/projects/mypiston2/target/debug/deps/libbitflags-518ea12e21428edd.rlib -Awarnings`
   Compiling num v0.1.22
     Running `rustc /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/num-0.1.22/src/lib.rs --crate-name num --crate-type lib -g -C metadata=798fe7e31b30dacd -C extra-filename=-798fe7e31b30dacd --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern rand=/home/me/projects/mypiston2/target/debug/deps/librand-7b0a3af7ae4685dc.rlib --extern rustc_serialize=/home/me/projects/mypiston2/target/debug/deps/librustc_serialize-70d93d5334da1e4e.rlib -Awarnings`
       Fresh log v0.3.1
       Fresh gl_common v0.0.4
       Fresh xml-rs v0.1.23
       Fresh draw_state v0.0.7 (https://github.com/gfx-rs/draw_state#44a0aed1)
       Fresh rand v0.3.7
   Compiling gl v0.0.12 (https://github.com/bjz/gl-rs#3ebf1cfe)
     Running `rustc /home/me/.cargo/git/checkouts/gl-rs-5020f97825182d66/master/gl/build.rs --crate-name build_script_build --crate-type bin -C prefer-dynamic -g --out-dir /home/me/projects/mypiston2/target/debug/build/gl-68546995ca960fc2 --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern khronos_api=/home/me/projects/mypiston2/target/debug/deps/libkhronos_api-4ca4e769faea81a4.rlib --extern gl_generator=/home/me/projects/mypiston2/target/debug/deps/libgl_generator-303adfd0fabbd040.rlib -Awarnings`
/home/me/.cargo/git/checkouts/rust-sdl2-8facfb557b6c1670/master/src/sdl2/lib.rs:4:1: 4:40 error: unstable feature
/home/me/.cargo/git/checkouts/rust-sdl2-8facfb557b6c1670/master/src/sdl2/lib.rs:4 #![feature(optin_builtin_traits, core)]
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/home/me/.cargo/git/checkouts/gfx_macros-20b8916c81d6b4ed/master/src/lib.rs:14:1: 14:77 error: unstable feature
/home/me/.cargo/git/checkouts/gfx_macros-20b8916c81d6b4ed/master/src/lib.rs:14 #![feature(collections, plugin_registrar, quote, box_syntax, rustc_private)]
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
/home/me/.cargo/git/checkouts/gfx-rs-93bce98024942039/master/src/lib.rs:18:1: 18:25 error: unstable feature
/home/me/.cargo/git/checkouts/gfx-rs-93bce98024942039/master/src/lib.rs:18 #![feature(alloc, core)]
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `sdl2`.

Caused by:
  Process didn't exit successfully: `rustc /home/me/.cargo/git/checkouts/rust-sdl2-8facfb557b6c1670/master/src/sdl2/lib.rs --crate-name sdl2 --crate-type lib -g --cfg feature="default" -C metadata=a064b7049d699f0c -C extra-filename=-a064b7049d699f0c --out-dir /home/me/projects/mypiston2/target/debug/deps --emit=dep-info,link -L dependency=/home/me/projects/mypiston2/target/debug/deps -L dependency=/home/me/projects/mypiston2/target/debug/deps --extern libc=/home/me/projects/mypiston2/target/debug/deps/liblibc-8c77960f0e8d4e86.rlib --extern sdl2_sys=/home/me/projects/mypiston2/target/debug/deps/libsdl2_sys-ae2c8ed03a451f47.rlib --extern rand=/home/me/projects/mypiston2/target/debug/deps/librand-7b0a3af7ae4685dc.rlib --extern bitflags=/home/me/projects/mypiston2/target/debug/deps/libbitflags-518ea12e21428edd.rlib -Awarnings` (exit code: 101)
me@me-desktop ~/projects/mypiston2 $
```

Call back:
```bash
me@me-desktop ~/projects/piston-examples/gfx_cube $ RUST_BACKTRACE=1 ./target/debug/piston-example-gfx_cube
thread '<main>' panicked at 'Error after executing command BindProgram(0): InvalidEnum', /home/me/.cargo/git/checkouts/gfx_device_gl-ceded8a9e751584e/master/src/lib.rs:194
stack backtrace:
   1:     0x7f26017bcc18 - sys::backtrace::write::he3059e6bc8c10ccbZGC
   2:     0x7f26017c07a7 - panicking::on_panic::h4b318d56839ed7af9TI
   3:     0x7f26017b32b3 - rt::unwind::begin_unwind_inner::hbbbefb3640cc608bhzI
   4:     0x7f26017b369f - rt::unwind::begin_unwind_fmt::ha9be29259324c678VxI
   5:     0x7f260177ee92 - Device::check::h64e7ba404d44dc6fpqd
                        at /home/me/projects/piston-examples/gfx_cube/<std macros>:9
   6:     0x7f26017849d7 - Device::process::h471f960cccf658d00rd
                        at /home/me/.cargo/git/checkouts/gfx_device_gl-ceded8a9e751584e/master/src/lib.rs:540
   7:     0x7f26017860d5 - Device.gfx..Device::reset_state::h60054d86db30abd2M0d
                        at /home/me/.cargo/git/checkouts/gfx_device_gl-ceded8a9e751584e/master/src/lib.rs:555
   8:     0x7f2601786340 - Device.gfx..Device::submit::h5ae65c1207968eb2s1d
                        at /home/me/.cargo/git/checkouts/gfx_device_gl-ceded8a9e751584e/master/src/lib.rs:561
   9:     0x7f26016adf8f - render::ext::device::Graphics<D, F>::end_frame::h3004895714909500234
                        at /home/me/.cargo/git/checkouts/gfx-rs-93bce98024942039/master/src/render/ext/device.rs:74
  10:     0x7f2601638330 - main::h71cd5ed00d645e32Jka
                        at src/main.rs:245
  11:     0x7f26017c44c8 - rust_try_inner
  12:     0x7f26017c44b5 - rust_try
  13:     0x7f26017c22fe - rt::lang_start::haa4bfb8b62dba5a7COI
  14:     0x7f26016385d4 - main
  15:     0x7f2600b31ec4 - __libc_start_main
  16:     0x7f2601635c48 - <unknown>
  17:                0x0 - <unknown>
me@me-desktop ~/projects/piston-examples/gfx_cube $
```

This happened after I updated rust today.

**Comment by kvark** [comment]
The compile errors are related, the call stack is something else (how did you run it if it fails to compile?)

**Comment by KingOfThePirates** [comment]
Sorry, I must have been tired last night. The compile errors are relevant. The call back is a different executable entirely. Fixing the comment now.

**Comment by scottopell** [comment]
I think this is related. Trying to build latest version from git (9299194). 

I'm new to rust, could anybody point me in the right direction for this? I've read up on traits and this still doesn't make much sense to me.

```sh
/Users/scott/code/rust/gfx-rs/src/render/mesh.rs:43:1: 46:2 error: parameter `Self` is never used
/Users/scott/code/rust/gfx-rs/src/render/mesh.rs:43 pub trait VertexFormat {
/Users/scott/code/rust/gfx-rs/src/render/mesh.rs:44     /// Create the attributes for this type, using the given buffer.
/Users/scott/code/rust/gfx-rs/src/render/mesh.rs:45     fn generate<R: Resources>(buffer: device::handle::RawBuffer<R>) -> Vec<Attribute<R>>;
/Users/scott/code/rust/gfx-rs/src/render/mesh.rs:46 }
/Users/scott/code/rust/gfx-rs/src/render/mesh.rs:46:2: 46:2 help: consider removing `Self` or using a marker such as `core::marker::PhantomFn`
error: aborting due to previous error
Could not compile `gfx`.
```

**Comment by kvark** [comment]
@scottopell thanks! It is related indeed. Please see https://github.com/gfx-rs/gfx-rs/pull/660 where `PhantomFn` was removed.

**Comment by kvark** [comment]
I created a [branch](https://github.com/gfx-rs/gfx-rs/tree/rust-1.0). Please submit your PRs to it, if you come up with some fixes for rust-1.0.

**Comment by scottopell** [comment]
That error was only seen on the current beta, but on the most recent nightly there are only a few warnings, no errors.

```
→ rustc -V
rustc 1.0.0-nightly (47def3ef2 2015-04-13) (built 2015-04-12)
→ cargo build
   Compiling libc v0.1.6
   Compiling bitflags v0.1.1
   Compiling draw_state v0.0.7 (https://github.com/gfx-rs/draw_state#44a0aed1)
   Compiling log v0.3.1
   Compiling gfx v0.2.5 (file:///Users/scott/code/rust/graphics_test)
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:44:1: 45:76 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:44 pub type BatchData<'a, R: Resources> = (&'a mesh::Mesh<R>, mesh::AttributeIter,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:45                                         &'a mesh::Slice<R>, &'a DrawState);
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:62:1: 68:3 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:62 pub type ImplicitBatch<'a, T: ShaderParam> = (
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:63     &'a mesh::Mesh<T::Resources>,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:64     mesh::Slice<T::Resources>,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:65     &'a ProgramHandle<T::Resources>,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:66     &'a T,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:67     &'a DrawState
                                                     ...
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:322:1: 327:3 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:322 pub type CoreBatchFull<'a, T: ShaderParam> = (
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:323     &'a CoreBatch<T>,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:324     &'a mesh::Slice<T::Resources>,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:325     &'a T,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:326     &'a Context<T::Resources>
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:327 );
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:378:1: 381:3 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:378 pub type RefBatchFull<'a, T: ShaderParam> = (
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:379     &'a RefBatch<T>,
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:380     &'a Context<T::Resources>
/Users/scott/code/rust/gfx-rs/src/render/batch.rs:381 );
/Users/scott/code/rust/gfx-rs/src/render/shade.rs:66:1: 66:88 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/render/shade.rs:66 pub type TextureParam<R: Resources> = (handle::Texture<R>, Option<handle::Sampler<R>>);
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/scott/code/rust/gfx-rs/src/render/mod.rs:45:1: 45:77 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/render/mod.rs:45 type CachedAttribute<R: Resources> = (handle::RawBuffer<R>, attrib::Format);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/scott/code/rust/gfx-rs/src/device/mod.rs:226:1: 230:3 warning: trait bounds are not (yet) enforced in type definitions [E0122]
/Users/scott/code/rust/gfx-rs/src/device/mod.rs:226 pub type SubmitInfo<'a, D: Device> = (
/Users/scott/code/rust/gfx-rs/src/device/mod.rs:227     &'a D::CommandBuffer,
/Users/scott/code/rust/gfx-rs/src/device/mod.rs:228     &'a draw::DataBuffer,
/Users/scott/code/rust/gfx-rs/src/device/mod.rs:229     &'a handle::Manager<D::Resources>
/Users/scott/code/rust/gfx-rs/src/device/mod.rs:230 );
   Compiling graphics_test v0.0.1 (file:///Users/scott/code/rust/graphics_test)
```

**Comment by kvark** [comment]
I don't like the fact our branches diverge, and we need to back-port changes from one to another (which we don't do due to lazyness). It would be great to have a single `master` branch with the `cfg(unstable)` enabled for the nightly build

**Comment by kvark** [comment]
I've merged the branch, and @csherratt made a nice hack for `Arc`. Only the macros are left.

**Comment by mitchmindtree** [comment]
:+1: :+1:
